# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 9, 15, 22, 11, 21051)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Order'),
        ),
    ]
