# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170409_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='customer',
        ),
    ]
